### PR TITLE
Preliminary PR for Alina's review of Web dev env setup code

### PR DESCRIPTION
**Pull request by Erin-Mounts**
...and for team walk-through and initial feedback.

The file of interest is the script file itself, BridgeDeveloperToolkit/BridgeDevSetupScript.sh. Everything else is just auto-generated for the Xcode project this lives in, for... reasons.

### CODE REVIEW

**Review by conundrumgirl — COMMENTED** [review]
I think it looks good. The ultimate check is if it works. If someone on bridge team can run this script and then is able to launch MTB locally  then I'd say it perfect.

**Comment by conundrumgirl** [comment]
To get started locally on 127.0.0.1: create .env.local file with `HOST=127.0.0.1` inside of it.
MTB starts on :3000 and arc on :3001
`yarn start` starts MTB
`yarn start:arc `start ARC

**Comment by syoung-smallwisdom** [comment]
Are we suppose to run the script using Xcode?

**Comment by Erin-Mounts** [comment]
No, I originally intended to do it that way but it requires too much interactive input.

**Pull request merged**
